build: use top-level build script for all levels

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,34 +1,42 @@
 #!/bin/bash
 
-function build {
-	echo "Building $1..."
+echo "Checking setup..."
 
-	go version >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	   echo "Go missing.  Install Go with:"
-	   echo ""
-	   echo "    sudo apt update"
-	   echo "    sudo apt install golang -y"
-	   echo ""
-	   exit 1
+go version >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+   echo "Go missing.  Install Go with:"
+   echo ""
+   echo "    sudo apt update"
+   echo "    sudo apt install golang -y"
+   echo ""
+   exit 1
+fi
+
+gcc --version >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+   echo "gcc missing.  Install gcc with:"
+   echo ""
+   echo "    sudo apt update"
+   echo "    sudo apt install gcc -y"
+   echo ""
+   exit 1
+fi
+
+sudo apt-get -y install libpam0g-dev >/dev/null 2>&1
+
+tmpFile="/tmp/$USER-merle-build"
+go list -f '{{.Dir}} {{.Target}}' ./... >$tmpFile
+
+while read -r line; do
+	args=($line)
+	if [ ! -z ${args[1]} ]; then
+		echo "Building ${args[1]}..."
+		cd ${args[0]}
+		go build ./...
+		go clean ./...
+		go install  ./...
+		sudo setcap CAP_NET_BIND_SERVICE=+eip ${args[1]}
 	fi
+done <$tmpFile
 
-	gcc --version >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	   echo "gcc missing.  Install gcc with:"
-	   echo ""
-	   echo "    sudo apt update"
-	   echo "    sudo apt install gcc -y"
-	   echo ""
-	   exit 1
-	fi
-
-	sudo apt-get -y install libpam0g-dev >/dev/null 2>&1
-
-	go build ./...
-
-	go install ./...
-	sudo setcap CAP_NET_BIND_SERVICE=+eip ~/go/bin/$1
-
-	ls -lh ~/go/bin/$1
-}
+rm $tmpFile
